"""Build evals/gold_queries.jsonl for Standard Model precision tuning."""

from __future__ import annotations

import json
from pathlib import Path

DOC_ID = "eb97c32131588801ccfbd07c41ce73ba752ca7e60a4c2ff56a8030e22f3356db"
OUT = Path("evals/gold_queries.jsonl")

# Verified chunk IDs from catalog (Standard Model only).
C = {
    "coleman_intro": "a1f694b32aa75dcf5b457873065477248912658a73f9e4fc946759fee1054fa6",
    "coleman_loopholes": "e2c9d2bdba81186a16ee19354eb7be0bb031bf0fe07b928f932b3f60a22b5af0",
    "goldstone_stmt": "4b34199b82b7976cde8f7c19c281b8f1494ebbe5634cbf86147829913e97e3d7",
    "goldstone_classical": "af938ce374b36ef29cf2403a2ebad517cb515a9ff56f0bd6ffa0b335043f5dc8",
    "goldstone_qft": "ca8e291bc94d5be93b7c68c6de52fa7810058fb767b2748c72cdcd05d22ba789",
    "abelian_higgs": "4034eb60ab128c1a619c454429818e06dc5ae2958bf7cc5d6d3401ecd62c65ad",
    "higgs_dof": "48ee38ceb0e32456f8f49cb43d21883cf1a13d6586b7ac5a1d078b43636fed9f",
    "meissner": "7e06477f66ca60381a3efecd384ac03dedd28fad227cd32f3f1904cdfb8193a7",
    "asymp_freedom": "f017d6d9e57c290af179e06f2200a1ff4455c8e456c10f8f61b1a936a867d224",
    "qcd_scale": "91344142d253e66b1dee410fd4e5284327cb48753df67eadaaec61fafef28fd6",
    "mass_gap": "0f3a8036750d17c0fb63a97b10ce1b89a8d38695c3dc9975c5b6998859b7028a",
    "confinement_short": "464212992de608f8e53408435a55a176179d6eb1d508b54dedcea7db0373e2a1",
    "hadrons": "20c4746766066bb4751fca78ffa9c2e35ff9951af28d894e01601c4248fb1757",
    "dirac_weyl": "962d309732d1c6055acf2c0ec3de94c0fb4dde9ab281f1dea4381ba8f0fbb175",
    "lorentz_j1j2": "19ab8db017fc1ddce5599b5ab31d8d86d0319f160136d6ebf9e377db0990a49b",
    "lorentz_noncompact": "1069bc69dc9e990183f38baecff68165dc09b795c26186e99e17b67799acc0de",
    "weinberg": "2b3bd0575dc587a40b3e7fffa26dc2f75e3b2e1d5f7ad925af8b980ce5fbb3a1",
    "ewsb_eat": "08305dc10f47db8657de0a67e10096dd725b055ba2cfd6b97aa4b8505e504b4d",
    "ckm": "48bdba048308a3ac58ae65d2b5c2a98c0e13bd12b89e8a0218f890e2a33556b4",
    "ckm_three": "c4e7be6acd33d54c481ec145f45818a7ce7bce5d8226d2a8eeeae436ae97e552",
    "cpt": "42bfe42aa70d0cb39d6449710fe5ab40ebf2b96f90be44b80068ae44ee05ce04",
    "cp_wherefore": "f5283d964fb0f7e87fa1f12ce9ce0ea22396f5e2115e9f2feb53f923c9c47d64",
    "parity": "03e955a45b317a21623894ae3d133ff9be68e06f03a1d64bf8bf7ea7eafd0883",
    "cmw": "b4b356a9990388a3d1371e387bc11e5cb9e986a90e896a9be5d37590c1d3acf0",
    "neutrino_osc": "18f6d2b978bd04dec6bcfcf94bff4d24f2b273a359f5c267ff11093d55afd23d",
    "neutrino_matter": "21e841cccb1345fa33070ecc0236f476f120f9545c99ea937248449f93b6b983",
    "axial_anomaly": "9db45cca7efabc16114354e7ecae85678b6bed2a89ad6d763c3fad61a84a1088",
    "eta_prime": "42168f68a8c81fae8255c6f3bd73269a62264497c5cbc0a1483d5797cf61959e",
    "confinement_csb": "ee8386c31c778783444a2d82d1fc05542d772b36e315fe0870a4ba8b245aafae",
    "gauge_inv": "a48ed4ce097b3189f83ecfac1b7607ebf6b3518d65d0ae3822514a035194fce0",
    "nonabelian_higgs": "ba7225eb3fc4a67da6e5bcd740316b0ca16e2b3a02ccd8fd8244d8361401518e",
}


def row(
    qid: str,
    typ: str,
    question: str,
    answer: str,
    chunks: list[str],
    tags: list[str],
    notes: str,
    pair_of: str | None = None,
    doc_id: str | None = DOC_ID,
) -> dict:
    return {
        "id": qid,
        "type": typ,
        "question": question,
        "reference_answer": answer,
        "relevant_chunk_ids": chunks,
        "doc_id": doc_id,
        "tags": tags,
        "pair_of": pair_of,
        "notes": notes,
    }


def main() -> None:
    exact: list[dict] = [
        row(
            "sm-exact-01",
            "exact",
            "What does the Coleman-Mandula theorem say about the symmetry group of an interacting quantum field theory?",
            "In spacetime dimension greater than 1+1, the symmetry group of any interacting QFT must factorise (Poincaré times internal symmetries).",
            [C["coleman_intro"]],
            ["coleman-mandula", "symmetries"],
            "Symmetries/Spacetime Symmetries/The Coleman-Mandula Theorem p22",
        ),
        row(
            "sm-exact-02",
            "exact",
            "According to Goldstone's theorem, how many massless Goldstone bosons arise when a continuous global symmetry G is spontaneously broken to H?",
            "The number is dim(G/H) = dim G - dim H.",
            [C["goldstone_stmt"]],
            ["goldstone", "ssb"],
            "Goldstone's Theorem in Classical Field Theory p72",
        ),
        row(
            "sm-exact-03",
            "exact",
            "What is the Abelian Higgs model?",
            "A complex scalar with Mexican-hat potential coupled to a U(1) gauge field.",
            [C["abelian_higgs"]],
            ["higgs", "abelian"],
            "The Abelian Higgs Model p83",
        ),
        row(
            "sm-exact-04",
            "exact",
            "What is the Meissner effect in a superconductor?",
            "Superconductors expel magnetic fields; the effect arises because the photon acquires a mass.",
            [C["meissner"]],
            ["meissner", "superconductivity"],
            "Meissner Effect p87",
        ),
        row(
            "sm-exact-05",
            "exact",
            "What is asymptotic freedom in Yang-Mills or QCD?",
            "The gauge coupling becomes weak at high energies / short distances so the theory is perturbatively simple there.",
            [C["asymp_freedom"]],
            ["asymptotic-freedom", "qcd"],
            "Asymptotic Freedom p100",
        ),
        row(
            "sm-exact-06",
            "exact",
            "What is meant by the mass gap in Yang-Mills theory?",
            "At strong coupling the quantum theory can differ completely from classical massless gluons; Yang-Mills is believed to have a mass gap set by the strong scale.",
            [C["mass_gap"]],
            ["mass-gap", "yang-mills"],
            "The Mass Gap p106",
        ),
        row(
            "sm-exact-07",
            "exact",
            "What is the difference between a Dirac spinor and a Weyl spinor as presented in these notes?",
            "A Dirac spinor is a 4-component spinor; Weyl spinors are the more fundamental 2-component left/right pieces needed for the Standard Model.",
            [C["dirac_weyl"]],
            ["spinors", "weyl", "dirac"],
            "Dirac vs Weyl Spinors p24",
        ),
        row(
            "sm-exact-08",
            "exact",
            "How is the Weinberg angle defined in electroweak theory?",
            "The Weinberg (weak mixing) angle is set by the SU(2) and U(1)_Y couplings, with tan θ_W = g'/g.",
            [C["weinberg"]],
            ["weinberg-angle", "electroweak"],
            "Electroweak Symmetry Breaking — Weinberg angle",
        ),
        row(
            "sm-exact-09",
            "exact",
            "What is the CKM matrix?",
            "The Cabibbo–Kobayashi–Maskawa matrix encoding quark flavour mixing in charged-current weak interactions.",
            [C["ckm"]],
            ["ckm", "flavour"],
            "The CKM Matrix p224",
        ),
        row(
            "sm-exact-10",
            "exact",
            "What does the CPT theorem imply about CP violation?",
            "By the CPT theorem, CP violation is equivalent to a violation of time reversal.",
            [C["cp_wherefore"]],
            ["cpt", "cp-violation"],
            "Wherefore CP Violation? p248",
        ),
        row(
            "sm-exact-11",
            "exact",
            "What is parity (P) as a spacetime transformation?",
            "Parity is an inversion of the spatial coordinates.",
            [C["parity"]],
            ["parity", "cpt"],
            "Parity p44",
        ),
        row(
            "sm-exact-12",
            "exact",
            "What does the Coleman-Mermin-Wagner theorem say about spontaneous breaking of continuous symmetries?",
            "A continuous symmetry cannot be spontaneously broken in quantum theories in d=0+1 (QM) or d=1+1; continuous SSB requires d=2+1 or higher.",
            [C["cmw"]],
            ["coleman-mermin-wagner", "ssb"],
            "Coleman-Mermin-Wagner Theorem statement p80-81",
        ),
        row(
            "sm-exact-13",
            "exact",
            "What are neutrino oscillations?",
            "Neutrinos produced in one flavour eigenstate can be detected in another because mass and flavour eigenstates differ.",
            [C["neutrino_osc"]],
            ["neutrino", "oscillations"],
            "Neutrino Oscillations §7.2",
        ),
        row(
            "sm-exact-14",
            "exact",
            "Why is there no light Goldstone boson associated with the U(1)_A axial symmetry of QCD?",
            "U(1)_A suffers an axial anomaly and was never a true quantum symmetry, so it is not available to be spontaneously broken; the would-be Goldstone is the heavy η'.",
            [C["eta_prime"]],
            ["axial-anomaly", "eta-prime", "qcd"],
            "Axial anomaly consequence — η' p168",
        ),
        row(
            "sm-exact-15",
            "exact",
            "How are finite-dimensional representations of the Lorentz algebra labelled?",
            "By a pair (j1, j2) with j1, j2 half-integers, coming from two su(2) subalgebras.",
            [C["lorentz_j1j2"]],
            ["lorentz", "representations"],
            "The Lorentz Group p14",
        ),
    ]

    paraphrase_specs = [
        (
            "sm-para-01",
            "sm-exact-01",
            "In an interacting relativistic QFT in more than two spacetime dimensions, how must spacetime and internal symmetries combine according to a famous no-go result?",
            "They must factorise: the symmetry algebra is a direct product of the Poincaré algebra with internal symmetries (Coleman–Mandula).",
            ["coleman-mandula", "symmetries"],
        ),
        (
            "sm-para-02",
            "sm-exact-02",
            "If a continuous global symmetry is spontaneously broken, how do you count the resulting massless scalar modes?",
            "Count the broken generators: dim G minus dim H.",
            ["goldstone", "ssb"],
        ),
        (
            "sm-para-03",
            "sm-exact-03",
            "Name the theory obtained by coupling a Mexican-hat complex scalar to electromagnetism (a U(1) gauge field).",
            "The Abelian Higgs model.",
            ["higgs", "abelian"],
        ),
        (
            "sm-para-04",
            "sm-exact-04",
            "Why do magnetic field lines get expelled from a superconducting material?",
            "Because the photon is massive inside the superconductor (Meissner effect).",
            ["meissner", "superconductivity"],
        ),
        (
            "sm-para-05",
            "sm-exact-05",
            "Why does QCD become easier to treat with perturbation theory at very short distances?",
            "Asymptotic freedom: the strong coupling runs to smaller values at high energy.",
            ["asymptotic-freedom", "qcd"],
        ),
        (
            "sm-para-06",
            "sm-exact-06",
            "Classically Yang-Mills has massless gluons; what qualitative feature is expected in the strongly coupled quantum theory at long distances?",
            "A mass gap — the spectrum starts at a nonzero mass scale set by Λ_QCD.",
            ["mass-gap", "yang-mills"],
        ),
        (
            "sm-para-07",
            "sm-exact-07",
            "For building the Standard Model, which spinor objects are emphasised as more fundamental than the four-component Dirac field?",
            "Weyl spinors (two-component left- and right-handed spinors).",
            ["spinors", "weyl"],
        ),
        (
            "sm-para-08",
            "sm-exact-08",
            "What angle mixes the SU(2) and hypercharge gauge fields into the photon and Z boson?",
            "The Weinberg angle (weak mixing angle) θ_W with tan θ_W = g'/g.",
            ["weinberg-angle", "electroweak"],
        ),
        (
            "sm-para-09",
            "sm-exact-09",
            "Which matrix describes how the weak charged current mixes quark generations?",
            "The CKM matrix.",
            ["ckm", "flavour"],
        ),
        (
            "sm-para-10",
            "sm-exact-10",
            "If CP is violated in a Lorentz-invariant theory, which other discrete symmetry must also fail?",
            "Time reversal, because of the CPT theorem.",
            ["cpt", "cp-violation"],
        ),
        (
            "sm-para-11",
            "sm-exact-11",
            "What discrete transformation flips the sign of all spatial coordinates?",
            "Parity (P).",
            ["parity"],
        ),
        (
            "sm-para-12",
            "sm-exact-12",
            "Why can you not spontaneously break a continuous symmetry in 1+1 dimensions?",
            "Coleman–Mermin–Wagner: continuous symmetries cannot be broken in d=0+1 or d=1+1 quantum theories.",
            ["coleman-mermin-wagner"],
        ),
        (
            "sm-para-13",
            "sm-exact-13",
            "How can a neutrino change apparent flavour between production and detection?",
            "Through neutrino oscillations arising from mismatched mass and flavour eigenstates.",
            ["neutrino", "oscillations"],
        ),
        (
            "sm-para-14",
            "sm-exact-14",
            "Why is the η' much heavier than the pions even though a chiral condensate might seem to break U(1)_A?",
            "Because the axial U(1) is anomalous and not a true quantum symmetry available for SSB.",
            ["axial-anomaly", "eta-prime"],
        ),
        (
            "sm-para-15",
            "sm-exact-15",
            "What pair of quantum numbers labels Lorentz algebra representations built from the two su(2) factors?",
            "(j1, j2) with each ji a non-negative half-integer.",
            ["lorentz", "representations"],
        ),
    ]

    exact_by_id = {r["id"]: r for r in exact}
    paraphrase: list[dict] = []
    for pid, pair, q, ans, tags in paraphrase_specs:
        base = exact_by_id[pair]
        paraphrase.append(
            row(
                pid,
                "paraphrase",
                q,
                ans,
                list(base["relevant_chunk_ids"]),
                tags,
                f"paraphrase of {pair}; {base['notes']}",
                pair_of=pair,
            )
        )

    multi: list[dict] = [
        row(
            "sm-multi-01",
            "multi",
            "State the Coleman-Mandula no-go result and name an important loophole that assumes a mass gap.",
            "Symmetries factorise as Poincaré × internal; a key loophole is conformal/massless theories where the mass-gap assumption fails (also supersymmetry).",
            [C["coleman_intro"], C["coleman_loopholes"]],
            ["coleman-mandula", "multi"],
            "statement + loopholes chunks",
        ),
        row(
            "sm-multi-02",
            "multi",
            "How does Goldstone's theorem for a global continuous symmetry change when the symmetry is gauged, as in the Abelian Higgs model?",
            "Globally you get dim(G/H) massless Goldstones; when gauged, the would-be Goldstone is eaten and gives the gauge boson a longitudinal mode / mass (Higgs mechanism).",
            [C["goldstone_stmt"], C["higgs_dof"]],
            ["goldstone", "higgs", "multi"],
            "Goldstone count + Higgs eating",
        ),
        row(
            "sm-multi-03",
            "multi",
            "Explain asymptotic freedom and define the QCD scale Λ_QCD that appears when the one-loop coupling diverges.",
            "The coupling weakens at short distance; Λ_QCD is the RG-invariant scale where the one-loop coupling blows up and strong coupling sets in.",
            [C["asymp_freedom"], C["qcd_scale"]],
            ["asymptotic-freedom", "qcd-scale", "multi"],
            "AF intro + Λ_QCD chunk",
        ),
        row(
            "sm-multi-04",
            "multi",
            "Relate the Meissner effect to the Abelian Higgs mechanism: why is a magnetic field expelled?",
            "In the Abelian Higgs / superconducting phase the photon is massive, so magnetic fields are energetically costly and are expelled (Meissner).",
            [C["meissner"], C["abelian_higgs"]],
            ["meissner", "higgs", "multi"],
            "Meissner + Abelian Higgs",
        ),
        row(
            "sm-multi-05",
            "multi",
            "How are Lorentz representations labelled, and why is the Lorentz group not simply SU(2)×SU(2)?",
            "Representations carry (j1,j2) from two su(2) algebras, but the Lorentz group is non-compact unlike compact SU(2)×SU(2) ≅ Spin(4).",
            [C["lorentz_j1j2"], C["lorentz_noncompact"]],
            ["lorentz", "multi"],
            "labels + noncompactness",
        ),
        row(
            "sm-multi-06",
            "multi",
            "In electroweak symmetry breaking, what happens to the would-be Goldstone modes and how does the Weinberg angle enter the gauge boson mass eigenstates?",
            "Would-be Goldstones ξ^A are eaten by the gauge fields; the massive neutral boson mixes W^3 and B via the Weinberg angle tan θ_W = g'/g.",
            [C["ewsb_eat"], C["weinberg"]],
            ["electroweak", "weinberg-angle", "multi"],
            "EWSB eating + Weinberg angle",
        ),
        row(
            "sm-multi-07",
            "multi",
            "What is the CKM matrix and how does its complex phase relate to time-reversal via CPT?",
            "CKM encodes quark mixing; its CP-violating phase implies T violation because CPT links CP violation to time-reversal violation.",
            [C["ckm"], C["cp_wherefore"]],
            ["ckm", "cpt", "multi"],
            "CKM + CPT/CP discussion",
        ),
        row(
            "sm-multi-08",
            "multi",
            "Why is there no light U(1)_A Goldstone in QCD, and how does 't Hooft anomaly matching relate confinement to chiral symmetry breaking?",
            "The axial U(1) is anomalous (η' heavy); separately, anomaly matching argues confinement implies chiral symmetry breaking.",
            [C["eta_prime"], C["confinement_csb"]],
            ["anomaly", "confinement", "multi"],
            "η'/anomaly + confinement⇒CSB",
        ),
        row(
            "sm-multi-09",
            "multi",
            "What is the Yang-Mills mass gap, and how does confinement organise quarks into hadrons?",
            "Strongly coupled Yang-Mills is expected to have a mass gap; confinement binds quarks into colour-singlet mesons and baryons (hadrons).",
            [C["mass_gap"], C["hadrons"]],
            ["mass-gap", "confinement", "multi"],
            "mass gap + hadrons",
        ),
        row(
            "sm-multi-10",
            "multi",
            "Describe vacuum neutrino oscillations and how the story changes when neutrinos propagate through matter.",
            "Flavour/mass mismatch causes oscillations in vacuum; in matter an additional effective Hamiltonian (MSW-like) modifies the oscillation pattern.",
            [C["neutrino_osc"], C["neutrino_matter"]],
            ["neutrino", "multi"],
            "vacuum osc + oscillations in matter",
        ),
    ]

    negatives: list[dict] = [
        row(
            "sm-neg-01",
            "negative",
            "What is the recommended daily insulin dose for type 2 diabetes?",
            "Not in corpus.",
            [],
            ["negative", "medicine"],
            "out of corpus",
            doc_id=None,
        ),
        row(
            "sm-neg-02",
            "negative",
            "How do I reset a forgotten AWS IAM root password?",
            "Not in corpus.",
            [],
            ["negative", "devops"],
            "out of corpus",
            doc_id=None,
        ),
        row(
            "sm-neg-03",
            "negative",
            "What is the capital of Mongolia and its 2020 population?",
            "Not in corpus.",
            [],
            ["negative", "geography"],
            "out of corpus",
            doc_id=None,
        ),
        row(
            "sm-neg-04",
            "negative",
            "Explain how blockchain consensus works in proof-of-stake Ethereum.",
            "Not in corpus.",
            [],
            ["negative", "crypto"],
            "out of corpus",
            doc_id=None,
        ),
        row(
            "sm-neg-05",
            "negative",
            "What baking temperature should I use for sourdough bread?",
            "Not in corpus.",
            [],
            ["negative", "cooking"],
            "out of corpus",
            doc_id=None,
        ),
        row(
            "sm-neg-06",
            "negative",
            "Summarise the plot of Shakespeare's Hamlet.",
            "Not in corpus.",
            [],
            ["negative", "literature"],
            "out of corpus",
            doc_id=None,
        ),
        row(
            "sm-neg-07",
            "negative",
            "What is the GAAP treatment of operating lease liabilities under ASC 842?",
            "Not in corpus.",
            [],
            ["negative", "accounting"],
            "out of corpus",
            doc_id=None,
        ),
        row(
            "sm-neg-08",
            "negative",
            "How does CRISPR-Cas9 edit the BRCA1 gene in clinical trials?",
            "Not in corpus.",
            [],
            ["negative", "biology"],
            "out of corpus",
            doc_id=None,
        ),
        row(
            "sm-neg-09",
            "negative",
            "What were the closing prices of NASDAQ on 1 January 2019?",
            "Not in corpus.",
            [],
            ["negative", "finance"],
            "out of corpus",
            doc_id=None,
        ),
        row(
            "sm-neg-10",
            "negative",
            "Describe the rules of Association Football offside as of World Cup 2022.",
            "Not in corpus.",
            [],
            ["negative", "sports"],
            "out of corpus",
            doc_id=None,
        ),
    ]

    all_rows = exact + paraphrase + multi + negatives
    assert len(all_rows) == 50, len(all_rows)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as f:
        for r in all_rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"wrote {len(all_rows)} rows to {OUT}")


if __name__ == "__main__":
    main()
